# Generated by Django 3.2.10 on 2022-01-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amt_pooled',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='usd_pooled',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
